### ISSUE TITLE
Graphical interface not displayed in EA 14.2 ultimate version

### ISSUE THREAD

**Issue by MatsGej** [Helmut-Ortmann/EnterpriseArchitect_hoTools#5] opened 2019-01-22 08:02 UTC
The Graphical interface not displayed in EA 14.2 ultimate version, only the line based by click on hotools in the ribbon. Not showing all the other good stuff from the graphical interface.

But it is displayed in the corporate version on another laptop. But it is pretty garbled at that machine. 

Most likely some setting in both cases. But which?

**Comment by Helmut-Ortmann** [comment] 2019-01-22 10:06
Hi MatsGej,

difficult to say without Screenshots, error messages. I'm not aware of any
settings related to graphical interface, dpi or so.

Have you downloaded the newest release from GITHUB? You find it at:
https://github.com/Helmut-Ortmann/EnterpriseArchitect_hoTools/releases

The settings you find in:
c:\Users\<user>\AppData\Roaming\ho\hoTools\user.config

You may send me the settings. Then I can try to reproduce it.

Best regards,

Helmut

**Comment by MatsGej** [comment] 2019-01-22 11:15
Hi Helmut,
The version number is 2.0.1.1 on my work laptop. The graphical interface is not shown at all, just the entry in the ribbon, where I can do certain things - starting with Create activity ....

I cananot get to the settings on the file system. The comapny has a lot of rules on what I can see. That is also causes a proble to update the version since there is a long process to do that.

The functionality I most want is the possibility to change the Line style on all connectors in one diagram. And will start to use the other functionalities later on.

I will send an update on the Graphical interface on my private laptop tonight.
BR
Mats

**Comment by Helmut-Ortmann** [comment] 2019-01-22 12:09
Hi Mats,

thanks for describing the issue. I can imagine it's not easy to copy with
company rules.

The current release hoTools is 3.2.13. It supports no admin install. Click
on the *.msi, Advanced, Next, etc. Please install this release.

Best regards,

Helmut

**Comment by Helmut-Ortmann** [comment] 2019-02-02 09:16
I close the issue because I can't reproduce. If the issue still exists feel free to reopen it with a description.

Thanks,

Helmut

**Closed as completed by Helmut-Ortmann** 2019-02-02 09:16 UTC
